# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "CentOS-6.4-x86_64"
  config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.define :jenkins do |jenkins| # [1]
      jenkins.vm.hostname = "vagrant.jenkins.com"
      jenkins.vm.network :private_network, ip: "192.168.33.10"
      jenkins.vm.network :forwarded_port, guest: 80, host: 8080
    end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file  = "site.pp"
    puppet.module_path = "puppet/modules"
    puppet.options = "--hiera_config /vagrant/puppet/hiera.yaml"
  end

end
